  %YAML:1.0

  #bag_path: /home/zhrobo/1544787797678722957
  pointcloud_port: 9696
  statusinfo_port: 9697
  remote_server: 192.168.0.133

  ip_address: 192.168.0.157
  usr_name: zhihui
  password: 123456
  connect_bash_file_path: ls
  start_bash_file_path: ~/start.sh
  end_bash_file_path: ~/end.sh

  points_file: /points.bin
  pose_file: /pose.txt
  cloud_out: /outcloud.las
  lidar_yaw: 0
  lidar_pitch: 90
  lidar_roll: 0
  lidar_x: -0.5
  lidar_y: 0
  lidar_z: 0.02571
  lidar_delay: 30
  lidar_period: 80
